import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cookieToInitialState } from "wagmi";
import { config } from "@/config";
import { headers } from "next/headers";
import Web3ModalProvider from "@/providers/web3-provider";
import Header from "@/components/shared/header";
import TabContainer from "@/components/shared/tabs";
import dynamic from 'next/dynamic'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ATOM Solution",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.svg"
  }
};

const HomeNoSSR = dynamic(() => import("./page"), { ssr: false })

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const initialState = cookieToInitialState(config, headers().get('cookie'))
  return (
        <Web3ModalProvider initialState={initialState}>
          <html lang="en">
            <body className={inter.className + ""}>
              <Header />
                <HomeNoSSR>
                  <TabContainer />
                  {children}
                </HomeNoSSR>
            </body>
          </html>
        </Web3ModalProvider>
  );
}
